### ISSUE TITLE
should the check scripts come into this repository?

### ISSUE THREAD

**Issue by jzuhone** [acisops/acis_thermal_check#38]
Less and less functionality is being farmed out to the various check scripts (e.g., `dpa_check`, `dea_check`, etc.).

I am beginning to wonder if we should revisit an idea that was rejected a few years ago--namely, that the various check tools should be subsumed under this package, `acis_thermal_check`. The user-facing part would be the same--the scripts run a load review. But often I find that if we have to make an API change somewhere in `acis_thermal_check` we still have moments where we have to touch all of the check tools at once. We're going to have a couple of those situations manifest themselves soon. 

What do folks think about this? Having only one or maybe two repositories, `acis_thermal_check` and `acisfp_check`, since the latter has plenty of its own customizations? But it now has even less than it did before, so I suspect that it could probably live in here too.

**Comment by jzuhone** [comment]
"assigning" to this issue is more like pinging

**Comment by taldcroft** [comment]
:+1: I think it would make perfect sense to have all the checkers in this one package. Each would be a separate module (with a command line entry script) mostly the same as the current ones. This will certainly reduce packaging and review effort.

My only disagreement is using Assignees to ping. :smile: I think doing @ mentions should do the trick, but no matter since we don't pay much attention to Assignee in our workflow.
